pipeline {
  options {
    buildDiscarder logRotator(artifactDaysToKeepStr: '', artifactNumToKeepStr: '', daysToKeepStr: '7', numToKeepStr: '5')
  }
  agent {
    node {
      label 'jenkins-2'
    }
  }
  environment {
    NPM_CONFIG_USERCONFIG = credentials('di2e-npm-dfntc-private')
  }
  stages {
    stage('Build es-home') {
      steps {
        sh 'NOSUDO=1 ./es-home/deploy/build-prod-container.sh'
      }
    }
  }
}
