pipeline {
    agent {
        node {
          label 'docker'
        }
    }
    stages {
        stage('Prepare') {
            agent {
                docker {
                    image node:14
                }
            }
            steps {
                script {
                    echo "hello"
                }
            }
        }
    }
}
