@startuml

skinparam {
    BackgroundColor #eee
}

title
  | header     | header     | header | header      | header      |
  | above-left | above-left | top    | above-right | above-right |
  | left-bar   | left       | center | right       | right-bar   |
  | left-bar   | left       | bottom | right       | right-bar   |
  | footer     | footer     | footer | footer      | footer      |
end title

@enduml