version: '3'
services:
    proxy:
        image: haproxy:1.8
        volumes:
            - "${PROXY_CFG}:/usr/local/etc/haproxy"
        expose:
        - 80
        - 443
        ports:
            - "127.0.0.1:8090:80"
        environment:
            - REACT_UI_PORT=${REACT_UI_PORT}
            - STATIC_PORT=${STATIC_PORT}

    react-ui:
        image: "node:12"
        user: "node"
        working_dir: /home/node
        volumes:
            - "./packages/react-ui:/home/node"
        expose:
            - ${REACT_UI_PORT}
        command: "npm run start"
        environment:
            - PORT=${REACT_UI_PORT}

    static-server:
        image: "node:12"
        user: "node"
        working_dir: /home/node
        expose:
            - ${STATIC_PORT}
        command: "npx http-server -e js"
        environment:
            - PORT=${STATIC_PORT}
        volumes:
            - ./assets/icons:/home/node/static/icons
            - ./packages/react-ui/node_modules/react/umd:/home/node/static/react
            - ./packages/react-ui/node_modules/react-dom/umd:/home/node/static/react-dom
            - ./packages/react-ui/node_modules/svg-injector/dist:/home/node/static/svg-injector
            - ./packages/ribbon/node_modules/@material:/home/node/static/material
            - ./packages/ribbon/dist/bgo:/home/node/static/ribbon
            - ./packages/security-banner/dist:/home/node/static/security-banner
